### ISSUE TITLE
create() calls are not resilient to additive API changes

### ISSUE THREAD

**Issue by spang** [nylas/nylas-ruby#245]
Previously, we made changes to this SDK intending to make it so that additive changes such as new keys on a model do not make the SDK blow up / error out. That is currently the case for fetching data (it merely emits a warning), but is NOT the case for create() calls.

Example code:
```created_event = api.events.create(
  title: "A fun event!",
  location: "The Party Zone",
  calendar_id: calendar.id,
  when: { start_time: Time.now + 60, end_time: Time.now + 120 })
```

If the API returns an unexpected field, the following error makes the script error:
```
    bundler: failed to load command: ./reproduce_bug.rb (./reproduce_bug.rb)
    Nylas::Registry::MissingKeyError: key ical_uid not in [:id, :object, :account_id, :calendar_id, :master_event_id, :message_id, :busy, :description, :location, :owner, :recurrence, :participants, :read_only, :status, :title, :when, :original_start_time]
      /home/spang/src/nylas/nylas-ruby/lib/nylas/registry.rb:30:in `rescue in []'
      /home/spang/src/nylas/nylas-ruby/lib/nylas/registry.rb:27:in `[]'
      /home/spang/src/nylas/nylas-ruby/lib/nylas/model/attributes.rb:48:in `cast'
      /home/spang/src/nylas/nylas-ruby/lib/nylas/model/attributes.rb:19:in `[]='
      /home/spang/src/nylas/nylas-ruby/lib/nylas/model/attributes.rb:25:in `block in merge'
      /home/spang/src/nylas/nylas-ruby/lib/nylas/model/attributes.rb:24:in `each'
      /home/spang/src/nylas/nylas-ruby/lib/nylas/model/attributes.rb:24:in `merge'
      /home/spang/src/nylas/nylas-ruby/lib/nylas/model.rb:35:in `save'
      /home/spang/src/nylas/nylas-ruby/lib/nylas/collection.rb:26:in `create'
      /home/spang/src/nylas/nylas-ruby/reproduce_bug.rb:40:in `<top (required)>'
```

**Comment by moui72** [comment]
what about updates and deletes?

**Comment by arunagw** [comment]
Seems like this has been fixed on latest version of gem. This was fixed in this commit https://github.com/nylas/nylas-ruby/commit/8a038d21b02c40c5b390ec44a7c94e88c5db252a and should not be an issue anymore. Please reopen this issue if you see this still an issue.
