### ISSUE TITLE
attributable.rb:26:in `assign': wrong number of arguments (given 1, expected 0) (ArgumentError)

### ISSUE THREAD

**Issue by mapf122** [nylas/nylas-ruby#251]
When attempting to call `nylas_client.messages.find(ID)`, I'm getting the following error:

```
/srv/root/vendor/bundle/ruby/2.7.0/gems/nylas-4.6.1/lib/nylas/model/attributable.rb:26:in `assign': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /srv/root/vendor/bundle/ruby/2.7.0/gems/nylas-4.6.1/lib/nylas/model.rb:63:in `reload'
	from /srv/root/vendor/bundle/ruby/2.7.0/gems/nylas-4.6.1/lib/nylas/collection.rb:130:in `find_model'
	from /srv/root/vendor/bundle/ruby/2.7.0/gems/nylas-4.6.1/lib/nylas/collection.rb:117:in `find'
```

I'll follow up with more info if I can reproduce this locally, but at the moment I'm getting this from a server I don't have direct access to. Any thoughts on what this could be?

**Comment by mapf122** [comment]
Figured it out.

**Comment by mapf122** [comment]
For anyone else with this problem, I think my code was passing `nil` to `nylas_client.messages.find()`
