### ISSUE TITLE
Version 4.6.3 breaks file downloading

### ISSUE THREAD

**Issue by bmulholland** [nylas/nylas-ruby#265]
I upgraded to nylas-ruby 4.6.3 and file downloads broke.

Root cause: As of 4.6.3, all non-Enumerable HTTP responses are assumed to be valid JSON and are run through `Yajl::Parser`. Obviously, that restriction doesn't apply to files (and perhaps other things?). There used to be a rescue that would handle when the response was invalid JSON, but [that was removed](https://github.com/nylas/nylas-ruby/commit/325cfb088c9a84765c08f1e9fdae2cea78bb3ef6#diff-06d584bc7b785ff8566d9cb6859f79d6014a96df95fcd562415e9a4d7d02d9edL134). (And it wasn't an ideal implementation anyway, IMO). So now, calling file.download results in:

```
     Yajl::ParseError:
       lexical error: invalid char in json text.
                                              %PDF-1.6 %????  1737 0 obj <</L
                            (right here) ------^
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nylas-4.6.3/lib/nylas/http_client.rb:138:in `parse'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nylas-4.6.3/lib/nylas/http_client.rb:138:in `parse_response'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nylas-4.6.3/lib/nylas/http_client.rb:85:in `block in execute'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/rest-client-2.1.0/lib/restclient/request.rb:834:in `process_result'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/webmock-3.11.0/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/webmock-3.11.0/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nylas-4.6.3/lib/nylas/http_client.rb:150:in `rest_client_execute'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nylas-4.6.3/lib/nylas/http_client.rb:84:in `execute'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nylas-4.6.3/lib/nylas/http_client.rb:104:in `get'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nylas-4.6.3/lib/nylas/file.rb:57:in `retrieve_file'
     # /Users/bmulholland/.rvm/gems/ruby-2.7.2@recital-backend/gems/nylas-4.6.3/lib/nylas/file.rb:28:in `download'
```

**Comment by snop-snov** [comment]
Have the same problem!
