### ISSUE TITLE
Nylas expanded message method is resetting the API object for every file

### ISSUE THREAD

**Issue by GlauberrBatista** [nylas/nylas-ruby#308]
I came to the following issue last week.
I'm using:
* Rails 5.2.5
* Ruby 2.6.7 (also happens on 2.5.7)
* Nylas 5.1.0 (also happens on 5.0.0)

If I do this:
```ruby
nylas_message.files.first.download
=> #<File:/var/folders/df/3__czmrj46xbmd8chnkbvk6h0000gn/T/query.png20210621-84115-1ukdi4u>
```
It works and downloads the file. The same happens with `#download!` method.

However, if I call the expanded method before download I got the following error:
```ruby
nylas_message.expanded.headers
=> #<Nylas::MessageHeaders:0x00007f995a145870
 @attributes=
  #<Nylas::Model::Attributes:0x00007f995a145640
   @attribute_definitions=
    #<Nylas::Registry:0x00007f99515188e8
     @registry_data=
      {:in_reply_to=>#<Nylas::Model::AttributeDefinition:0x00007f99515187f8 @default=nil, @exclude_when=[], @type_name=:string>,
       :message_id=>#<Nylas::Model::AttributeDefinition:0x00007f9951518500 @default=nil, @exclude_when=[], @type_name=:string>,
       :references=>#<Nylas::Model::ListAttributeDefinition:0x00007f9951518258 @default=[], @exclude_when=[], @type_name=:string>}>,
   @data=
    #<Nylas::Registry:0x00007f995a1454b0
     @registry_data=
      {:in_reply_to=>"<BL0PR07MB40494C56E4D258514228815CBC0D9@BL0PR07MB4049.namprd07.prod.outlook.com>",
       :message_id=>"<CAEyPB0wtYqL=j2rFvuXLjtqaVtQJGV2wiiyjkDfa3vga72oGZQ@mail.gmail.com>",
       :references=>["<BL0PR07MB40494C56E4D258514228815CBC0D9@BL0PR07MB4049.namprd07.prod.outlook.com>"]}>>>
 
nylas_message.files.first.download
NoMethodError: undefined method `get' for nil:NilClass
Did you mean?  gem
from /Users/glauberbatista/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/nylas-5.1.0/lib/nylas/file.rb:59:in `retrieve_file'

nylas_message.files.first.download!
NoMethodError: undefined method `get' for nil:NilClass
Did you mean?  gem
from /Users/glauberbatista/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/nylas-5.1.0/lib/nylas/file.rb:59:in `retrieve_file'
```
Checking https://github.com/nylas/nylas-ruby/blob/v5.1.0/lib/nylas/file.rb#L59 I found that the `api` object is empty and that only happens when I call the `#expanded` method first.

I had to do the following workaround to make it work:
```ruby
api = nylas_message.api.clone
in_reply_to = nylas_message.expanded.headers.in_reply_to
message_id = nylas_message.expanded.headers.message_id
nylas_message.files.each do |file|
  file.api = api
end
```

**Comment by mrashed-dev** [comment]
Thanks for raising this issue, we will take a look at it!

**Comment by mrashed-dev** [comment]
The issue has been identified and fixed - when we merged the attributes from the response body of the expanded call, the `api` object was not being transferred from the message object to the newly-modified `files` array. Now we make sure we manually invoke the function. This fix will be available in the next release!

**Comment by GlauberrBatista** [comment]
Thank you
