### ISSUE TITLE
LoadError: cannot load such file -- active_support/core_ext/hash

### ISSUE THREAD

**Issue by etagwerker** [nylas/nylas-ruby#79]
When I follow the instructions in https://nylas.com/docs/platform#server_side_explicit_flow I run into this boot error: 

```
Boot Error

Something went wrong while loading config.ru

LoadError: cannot load such file -- active_support/core_ext/hash

/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/nylas-2.0.1/lib/nylas.rb:6:in `require'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/nylas-2.0.1/lib/nylas.rb:6:in `<top (required)>'
/Users/etagwerker/Projects/nylas-test/app.rb:2:in `require'
/Users/etagwerker/Projects/nylas-test/app.rb:2:in `<top (required)>'
config.ru:1:in `require'
config.ru:1:in `block in inner_app'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `inner_app'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:113:in `eval'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:113:in `inner_app'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:103:in `assemble_app'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/shotgun-0.9.1/lib/shotgun/favicon.rb:12:in `call'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/Users/etagwerker/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/etagwerker/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/etagwerker/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/etagwerker/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

It seems that you haven't declared `activesupport` as a dependency of this gem. See: https://github.com/nylas/nylas-ruby/blob/master/nylas.gemspec#L63-L92

I can submit a PR to add this dependency.

**Comment by pfista** [comment]
Fixed in 89c59a714ed1fd9bbd91522aaf85a6b638cc10fe
